### ISSUE TITLE
Create a monorepo of all parity JS libs

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/fether#122]
1. There are a lot of used and unused JS libs in the parity-js org. I want to create a monorepo of all JS libs used at parity.

It would go in `paritytech/js-libs`, and would contain
- [`@parity/api`](https://github.com/parity-js/api)
- [`@parity/abi`](https://github.com/parity-js/abi)
- [`@parity/jsonrpc`](https://github.com/parity-js/jsonrpc)
- `@parity/contracts`, which would contain [this folder](https://github.com/parity-js/shared/tree/master/src/contracts)
- [`@parity/light.js`](https://github.com/parity-js/light.js)
- `@parity/light.js-react`, which is [this](https://github.com/paritytech/fether/tree/master/packages/light-hoc)
- `@parity/electron`, which is [this](https://github.com/paritytech/fether/tree/master/packages/parity-electron)

Note: a monorepo would really suit here.

~2. In a second step, create a monorepo of JS libs unmaintained by Parity and put it under the community-driven parity-js org: `@parity/ui`, `@parity/mobx`, `@parity/etherscan`, `@parity/shapeshift`...~

@jacogr Any other ideas about this?

PS: Not entirely related to Fether, but it's still the best place to put this since this repo is currently hosting two of those libraries.

**Comment by jacogr** [comment]
As discussed, 100% agreed with the approach.

**Comment by amaurymartiny** [comment]
Done. https://github.com/paritytech/js-libs.
