### ISSUE TITLE
Code Review, volunteers needed

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/fether#124]
@jacogr was reviewing the code in the beginning and provided useful input, but since he's not working on the codebase and it grew bigger, at one point it was becoming useless for him to review all PRs, esp. architecture-wise.

So I'm looking for volunteers to help me review the code before we ship Fether.

# Guideline

- I put a list of files/folders in the table below, with some info about each item such as *severity* (security-wise) or *difficulty of review* (how easy would it be to review the item).
- You choose one or several items from the table, and for each item, complete the **Review Template** (inspired from [Yelp](https://engineeringblog.yelp.com/2017/11/code-review-guidelines.html#when-doing-a-code-review)).
- Create a reply in this github thread for each item you review, see **Example**. If you think the review doesn't pass and the code needs change, then open a separate Github issue.

### Review Template

<details><summary>click to expand</summary>
<p>

**Item:** `name of the item in the table`

- [ ] Understand the code. _Make sure you completely understand the code_
- [ ] Check code quality. _Check for well-organized and efficient core logic. Is the code as general as it needs to be, without being more general that it has to be? Make sure the code is maintainable._
- [ ] Verify that the code is tested well. _Confirm adequate test coverage. Check tests having the right dependencies and are testing the right things._
- [ ] Check for any security holes and loop.
- [ ] Answer: If this code breaks at 3am and you’re called to diagnose and fix this issue, will you be able to?

**Comments:** `comments if any`
</p>
</details>

### Example

<details><summary>click to expand (this should be one reply in this thread)</summary>
<p>

**Item:** `myFile.js`

- [x] Understand the code.
- [x] Check code quality.
- [ ] Verify that the code is tested well.
- [x] Check for any security holes and loop.
- [x] Answer: If this code breaks at 3am and you’re called to diagnose and fix this issue, will you be able to?

**Comments:** `Missing some tests, and I think they should be required here. Will open a new github issue for this.`
</p>
</details>

# Review Items

| Name                                                                                                                                  | Description                                                  | Severity | Difficuty | Comments                                                                                                                                                                     |
| ------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ | -------- | --------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [MobX sendStore.js](https://github.com/paritytech/fether/blob/master/packages/fether-react/src/stores/sendStore.js)                   | Logic for sending tx                                         | High     | Easy      | Make sure that we're sending the correct tx.                                                                                                                                 |
| [MobX parityStore.js](https://github.com/paritytech/fether/blob/master/packages/fether-react/src/stores/parityStore.js)               | Require a secure token from the node                         | Medium   | Medium    | Make sure that this token is securely stored.                                                                                                                                |
| [@parity/light.js](https://github.com/paritytech/js-libs/tree/master/packages/light.js)                                                                             | High-level Reactive JS lib (oo7-parity with RxJS)            | Medium   | Difficult | Can be skipped now, as it's a big codebase. Will create a similar issue as this one on that repo. It might make sense now to have a look at the Readme though. |
| [@parity/light.js-react](https://github.com/paritytech/js-libs/tree/master/packages/light.js-react)                                         | Using `parity/light.js` with React (equivalent of oo7-react) | Medium   | Easy    |                                                                                                                                                                |
| [MobX createAccountStore.js](https://github.com/paritytech/fether/blob/master/packages/fether-react/src/stores/createAccountStore.js) | Logic to create an account                                   | Medium   | Easy      | Holds the user's secret phrase at some point.                                                                                                                                |
| [fether-electron](https://github.com/paritytech/fether/tree/master/packages/parity-electron)                                          | Electron wrapper                                             | Medium   | Medium    | Make sure [Electron's guide](https://electronjs.org/docs/tutorial/security) is followed                                                                                      |
| [@parity/electron](https://github.com/paritytech/fether/tree/master/packages/parity-electron)                                         | Interaction between Parity and Electron                      | Low      | Medium    |                                                                                                                                                                              |
| [Other Mobx Stores](https://github.com/paritytech/fether/tree/master/packages/fether-react/src/stores)                                | The rest of the MobX stores (other than the 3 above)         | Low      | Easy      | Non-critical logic                                                                                                                                                           |
| [React app](https://github.com/paritytech/fether/tree/master/packages/fether-react)                                                   | React app                                                    | Low      | Easy      | Contains minimal logic, only UI and UI state changes (all logic is in MobX stores)                                                                                                                        |
| [fether-ui](https://github.com/paritytech/fether/tree/master/packages/fether-ui)                                                      | UI Buildling Blocks Components                               | Low      | Easy      |                                                                                                                                                                              |

It would be recommendable to get High- and Medium-severity items reviewed before shipping.

**Comment by axelchalon** [comment]
**Item:** `fether-electron`

- [x] Understand the code.
- [x] Check code quality.
- [ ] Verify that the code is tested well.
- [x] Check for any security holes and loop.
- [x] Answer: If this code breaks at 3am and you’re called to diagnose and fix this issue, will you be able to?

**Comments:** Made some small fixes here https://github.com/paritytech/fether/pull/163. Some CLI corner cases still need to be fixed (and the CLI-handling code refactored) ; I'll do this in a subsequent PR.

**Comment by axelchalon** [comment]
**Item:** `@parity/electron`

- [x] Understand the code.
- [x] Check code quality.
- [ ] Verify that the code is tested well.
- [x] Check for any security holes and loop.
- [x] Answer: If this code breaks at 3am and you’re called to diagnose and fix this issue, will you be able to?

**Comments:** ditto

**Comment by axelchalon** [comment]
**Item:** `MobX parityStore.js`

- [x] Understand the code.
- [x] Check code quality.
- [ ] Verify that the code is tested well.
- [x] Check for any security holes and loop.
- [x] Answer: If this code breaks at 3am and you’re called to diagnose and fix this issue, will you be able to?

**Comments:** custom wsInterface/wsPort doesn't work. fix in https://github.com/paritytech/fether/pull/181/commits/764127af1fa8a454d866f51cea5758cfdd5a0558

**Comment by ltfschoen** [comment]
Update fether-electron to incorporate electron aspects of https://github.com/parity-js/shell

**Comment by Tbaut** [comment]
Closing this as we'll have an external audit.
