### ISSUE TITLE
Suggestion: Add help icon with a section showing where password encrypted keys are stored on device

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#130]
i.e. using the default kovan chain on macOS the created keys are stored at ~/Library/Application Support/io.parity.ethereum/keys/kovan. some users may not be aware that different Parity wallets use/store keys in the same folder on the user device. if the user knows this upfront it may be easier for them to just copy/paste their key file into the directory

**Comment by Tbaut** [comment]
You are thinking about power users, I would not like to talk to beginner/normal users, about copying their keys around. We will prob- have in v0.2 the ability to import accounts with JSON keyfiles. This should be enough I guess.
