### ISSUE TITLE
Suggestion: Show current chain and allow user to change chain

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#131]
* the UI doesn't show what chain i'm connected (i understand it's connected to kovan because it added encrypted keys after i created an account to the ~/Library/Application Support/io.parity.ethereum/keys/kovan folder on my computer)
* it doesn't give me the option to change chain (i.e. from kovan and mainnet)
* it doesn't show me a help icon with step-by-step instructions on how to manually change chains from the CLI if i'm a developer
* after clicking an account that i've created, if i click "Add tokens" and enter say "dot" to search for DOT tokens, it returns no results or feedback, such as a suggestion to change to a different chain

**Comment by Tbaut** [comment]
Valid concern. This is a feature (for now). We do not want people to think about this. It will be launched as an alpha on Kovan. Later on, on Mainnet (beta?). We want to make it easy for beginner users, and they should not care about Kovan IMO.

Could be a good feature for later releases

**Comment by bjornwgnr** [comment]
I think that as long as Fether's functionality is limited to sending ETH/tokens and showing account balances, it is fine that Fether doesn't offer chain selection. Perhaps we should publish two binaries though:
- alpha/beta: kovan only
- beta/stable: mainnet only
