### ISSUE TITLE
Import account and changing the username does not initially display a username in the Accounts list or display correctly on the Account page  

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#138]
After clicking "Confirm Account Creation" as described in [Issue #137](https://github.com/paritytech/fether/issues/137), it then took me back to the "Accounts" page, and it still showed the same two accounts that I initially created earlier as expected. The second account no longer had a username of "account2" that I initially associated with it... instead for about 2 seconds it displayed "account3" as expected, but then it changed and displayed "(No name)" for the username of the second account and it stayed that way. 

I then clicked the second account that now had a username of "(No name)" and it changed to the page where it shows your Ethereum balance, but instead of showing the username and password at the top as expected, it just showed the grey blending animation instead at the top (indicating that it was trying to load the username/address)... so i navigated back to the accounts list and clicked the first account with username of "account1" instead, and found that that account worked as expected and showed the username and account address correctly above the Ethereum balance.

**Comment by amaurymartiny** [comment]
Yes, bug.

We should prevent the user from importing an account that's already in the list.

**Comment by fckt** [comment]
or maybe warn, at least? Maybe she/he just forgot the password for the account and trying to recover it from the phrase..
