### ISSUE TITLE
Parity Signer integration

### ISSUE THREAD

**Issue by fckt** [paritytech/fether#146]
An obvious request from me ☺️
https://github.com/paritytech/parity-signer

For inspiration:
https://github.com/MyCryptoHQ/MyCrypto/pull/1349

There was #5 , but it's closed

**Comment by Tbaut** [comment]
This is one of the majors feature whished for the next iteration (v0.3?)

**Comment by axelchalon** [comment]
Do we hide "Export into JSON" for Parity Signer accounts? cf https://github.com/paritytech/fether/pull/260

**Comment by Tbaut** [comment]
Good point, we can't generate any JSON AFAIK so we should hide/deactivate this feature indeed.
