### ISSUE TITLE
Syncing 100% 

### ISSUE THREAD

**Issue by fckt** [paritytech/fether#147]
Just left the app open for a day..

<img width="359" alt="screen shot 2018-07-09 at 2 54 55 am" src="https://user-images.githubusercontent.com/547167/42425322-601921f6-8324-11e8-97f9-33fb19c3d255.png">

**Comment by fckt** [comment]
looks like connection was lost at some point. Maybe that's related to parity-ethereum itself..

**Comment by Tbaut** [comment]
Yeah this is a light client problem, basically loosing peers :(
