### ISSUE TITLE
Element highlighting overlaps

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/fether#149]
<img width="364" alt="screen shot 2018-07-09 at 12 45 12" src="https://user-images.githubusercontent.com/17831185/42449666-da4700da-8381-11e8-98e1-6df0a17e17fd.png">

<img width="364" alt="screen shot 2018-07-09 at 12 45 18" src="https://user-images.githubusercontent.com/17831185/42449685-e89e2b22-8381-11e8-892b-147b0a868a26.png">

**Comment by Tbaut** [comment]
I noticed it before, I wondered if this is a problem. We could remove the blackground color change on mouse hover.

**Comment by Tbaut** [comment]
There is no easy solution for that one I'afraid as we don't want to enlarge the window or reduce the size of the address (would be too small). Removing the background color makes it a little confusing...

Please reopen if this is *really* disturbing you :)
