### ISSUE TITLE
Fether doesn't work when light node is restarted with different chain

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/fether#151]
Probably not a bug at this point. When the node is being restarted with a different chain after Fether was started, Fether doesn't re-pull available accounts (and therefore shows the accounts for the initial chain) and doesn't react to any clicks. Fether starts working as expected again once node is restarted to connect to initial chain.

**Comment by Tbaut** [comment]
I think you said it! Fether is not (yet?) really meant to switch between chains :)
