### ISSUE TITLE
Disable Popup once user clicks on any other form fields on Tx sending screen!

### ISSUE THREAD

**Issue by Rakhisharma** [paritytech/fether#167]
On Tx sending screen once user click on `To` form filed, user can see the popup `Please enter a valid Ethereum address`, later when user clicks on any other form field(without entering address)  popup is not getting away. As you see in the screenshot I am still entering amount that I want to send.

![screenshot from 2018-07-30 12-16-01](https://user-images.githubusercontent.com/9638740/43381734-3826f36e-93f3-11e8-8740-c0a6cfcd255c.png)

How to reproduce:

Click on `to` form field on Tx Sending screen, Do not enter anything in `to` field. Just click on any other form filed of screen- popup stays there always!

**Comment by Tbaut** [comment]
Sure, there is still no valid address in there.. so I don't really see the problem :)
