### ISSUE TITLE
Fether shouldn't download Parity if Parity was not found on the machine but is still running

### ISSUE THREAD

**Issue by axelchalon** [paritytech/fether#175]
We should try `isParityRunning` before `getParityPath`

**Comment by amaurymartiny** [comment]
There's one problem: how to get the signer token?

**Comment by axelchalon** [comment]
Considering Fether is meant for general use, I think this issue is trivial, but I think it would be best, if Parity is running but we cannot locate the executable, to ask the user to run `parity signer new-token` manually.
Downloading Parity just to run `parity signer new-token` wouldn't make much sense since it would most likely not share the same config folders as the running instance of parity (typically in tunnelling use cases)
