### ISSUE TITLE
Fether doesn't have any logo/icon on linux

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#190]
Installing though the latest tar.gz on GitHub as well as `yarn package`.
Same for the .deb (created by the above command):
![image](https://user-images.githubusercontent.com/33178835/44728547-14e75780-aadd-11e8-97fd-8cca44e931f4.png)

**Comment by Tbaut** [comment]
Yup I can confirm, the 512 icon trick didn't work

**Comment by amaurymartiny** [comment]
.snap has icon for Tbaut too. So only .deb and .tar.xz don't. And AppImage?

**Comment by Tbaut** [comment]
AppImage is broken cf. https://github.com/paritytech/fether/issues/166

**Comment by Tbaut** [comment]
not solved :(
