### ISSUE TITLE
Unhandled error: Timeout for On-demand query

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#201]
Sending a transaction was successful (I could tell after refreshing) but the PR https://github.com/paritytech/parity-ethereum/pull/9318 involves a new scenario that is not handled well by Fether:
```
eth_getTransactionReceipt: -32065: Timeout for On-demand query; 5 query attempts remain for query #0
```

![image](https://user-images.githubusercontent.com/33178835/45483533-7d773b00-b751-11e8-8b1f-e329ef40a02c.png)

**Comment by amaurymartiny** [comment]
Probably better to solve the upstream error: https://github.com/paritytech/parity-ethereum/issues/9133.

The error display on Fether could be improved, but that's a detail.
