### ISSUE TITLE
"Import account" should have warning/info that only a parity recovery phrase can be used

### ISSUE THREAD

**Issue by chrisdotn** [paritytech/fether#202]
When using the `Import Account` feature, fether asks for the recovery phrase. Because fether is using parity to generate the priv/pub keys, only recovery phrases that were generated by parity can be used. Fether should display an info so that users do not get confused. 

In particular, they cannot use a mnemonic that has been generated by one of the other clients that relies on the [BIP39 wordlist](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md), instead of on the [parity wordlist](https://github.com/paritytech/wordlist).

**Comment by joshua-mir** [comment]
Maybe related to #199

**Comment by Tbaut** [comment]
Thanks. Fether's target is beginner users. Talking about BIP39 is way too advanced IMO. https://github.com/paritytech/fether/issues/100 should let them know that the word they entered is not valid/supported by this Wallet.

We expect to have [JSON import](https://github.com/paritytech/fether/issues/101) support in future versions also.

Closing as duplicate.
