### ISSUE TITLE
Bundle Parity Ethereum in Fether's binary

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#204]
From user study:
As a user, I would like to download one unique binary, and not have to wait for another binary (Parity Ethereum) to get downloaded when I launch Fether.

**Comment by amaurymartiny** [comment]
Why not. The only small downside I see is that we need to +/- tie PE and Fether releases together, or else the hardcoded header will be quite old.

**Comment by Tbaut** [comment]
Good point, however, if you DL Fether once, launch it (and DL PR) and then relaunch fether in 2 months, it will not fetch a new parity version will it?
The hardcoded header is updated manually atm by me every month or so. This might be a problem in the future when we don't update Fether too often. Let's hope we've found a better way to sync by this time :)

**Comment by amaurymartiny** [comment]
Discussing with @Tbaut, one solution would be:
- bundle parity-ethereum
- run it with `--auto-update=all --release-track=beta`

**Comment by Tbaut** [comment]
> Discussing with @Tbaut, one solution would be:
>- bundle parity-ethereum
>- run it with --auto-update=all --release-track=beta

Update: this wouldn't allow Parity Ethereum to be updated because auto-update only works for fully synced full nodes.

The recent past has shown us that many critical releases of Parity Ethereum can be delivered in a short time frame (e.g Constantinople release, followed by a ConstantiNOPEl release a couple days after and a new release for StPetersburg or whatever will be its name). This could also affect Security releases that need to be spread as quickly as possible.

I suggest to:
- bundle a Parity Ethereum release to Fether (at CI level). 
- at Fether launch, if the number of blocks to sync is say > 260000 (the equivalent of 45 days @ 15s block time) we should relaunch parity after a `db kill` to eventually benefit from an update of the hardcoded headers.
- A better solution would be to know if we are currently syncing blocks that are before the hardcoded header.

**Comment by axelchalon** [comment]
Would require implementation of Fether updating (https://github.com/paritytech/fether/issues/313) prior to this

**Comment by axelchalon** [comment]
I think that as a stepping stone we could define in the code (package.json) the minimum Parity Ethereum version required (needed for https://github.com/paritytech/fether/pull/394 for example), and if the Parity Ethereum we're launching is older, then warn the user or download newer version. wdyt?

**Comment by Tbaut** [comment]
If for some reason parity ethereum becomes non compatible with Fether (one example could have been the account management removal where a new version of the node would be incompatible with any version of Fether). We can still change this behavior in the future to require a specific version of Parity. So I agree with that. The lastest should be good.

But are we still talking about shipping both binaries together?

**Comment by amaurymartiny** [comment]
In my mind bundling is not that big a task, it's only a bash script that will:
- download the correct version of parity
- copy it in the `__static` folder (which will then be bundled as-is in the binary)
- and electron will run the binary inside `__static`.

I think it's worth to spend half a day to see how easy this task is (I might be totally wrong), and if not easy, then the stepping stone sounds good.

**Comment by Tbaut** [comment]
Got it. That's actually a first step toward https://github.com/paritytech/fether/issues/313 then. Those 2 issues are a must IMO for security reasons before having Fether on Mainnet.

**Comment by axelchalon** [comment]
I'll get started on this tomorrow
