### ISSUE TITLE
Importing already existing account buggy

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/fether#234]
Importing an already existing account (e.g. named "Test1") and naming the new one e.g. "Test2" leads to having one single account named "(No name)".

Suggestion: Show error message. (Alternatively, replace old account with new account (name & password)?)

**Comment by Tbaut** [comment]
Do I understand well that you had this problem by importing twice the same account right?

**Comment by bjornwgnr** [comment]
Account was already created - tried to import the same account via seed with a new name/pw.

**Comment by axelchalon** [comment]
related to https://github.com/paritytech/fether/issues/138

**Comment by Tbaut** [comment]
My bad. I thought this was fixed earlier. Closing in favor of the above mentioned issue.
