### ISSUE TITLE
"Next" button flickers when click "Generate Another Icon" on "Create a new account" page

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#243]
on the "Create a new account" page, each time i click the "GENERATE ANOTHER ICON" the "(NEXT)" button flickers. is this desired behaviour?

**Comment by Tbaut** [comment]
Probably not :roll_eyes: but that's a nit :) Closing to keep the backlog clean for more important things.

**Comment by axelchalon** [comment]
While the new icon/address is being generated, the "next" button is disabled. Is this what you mean?
