### ISSUE TITLE
Tooltip of "To" input field on "Send Ether" page obstructs "Amount" input value

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#245]
on the "Send Ether" page, if i click the input field of the "To" section but don't enter anything and then click elsewhere, it displays a tooltip "Please enter a valid Ethereum address", which obstructs the input value of the "Amount" field. could we make that tooltip slightly wider so it doesn't wrap over two lines (i.e. so the text "address" is on the same line as "Please enter a valid Ethereum")?

<img width="353" alt="screen shot 2018-11-10 at 19 26 06" src="https://user-images.githubusercontent.com/6226175/48304978-5bb4ed00-e523-11e8-836a-d91833c871a3.png">

**Comment by Tbaut** [comment]
That really a nit, I don't think it would be nice.
Closing not to have too many nits in the backlog, our capacity is reduced (unless you are willing to do some PRs :) )
