### ISSUE TITLE
Show input field validation error tooltip on "Send Ether" page only for the input field currently in focus

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#246]
on the "Send Ether" page,  if i click the input field of the "To" section but don't enter anything and then click elsewhere, it displays a tooltip "Please enter a valid Ethereum address". 
if i then click the "Amount" input field and enter an invalid value like "+-eE.,", even though the "Amount" input field is in focus with the cursor, it still shows the tooltip "Please enter a valid Ethereum address" that's associated with the "To" input field, when I think it should display the tooltip associated with the "To" input field of "Please enter a valid amount" instead.
and if both input fields are invalid, could we only display the tooltip associated with the input field where our cursor is?

in screenshot above the "Amount" input field is in focus with the cursor, but 
<img width="354" alt="screen shot 2018-11-10 at 20 04 02" src="https://user-images.githubusercontent.com/6226175/48304997-ac2c4a80-e523-11e8-8665-90cd743e88af.png">

**Comment by Tbaut** [comment]
>if both input fields are invalid, could we only display the tooltip associated with the input field where our cursor is?

No because if nothing is focused the user can't send but doesn't know why (well he prob. knows but he has to click somewhere extra !).
