### ISSUE TITLE
Dot point changes into a comma when pasting a decimal value into the "Amount" input field on the "Send Ether" page 

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#249]
If I go to and paste "0.0001260000000000705" into the "Amount" input field, then when I click somewhere else the value in the "Amount" input field changes to "0,0001260000000000705" (it replaces the dot point `.` with a comma `,`)

<img width="356" alt="screen shot 2018-11-10 at 22 31 33" src="https://user-images.githubusercontent.com/6226175/48306433-b86ed280-e538-11e8-9937-ae8495d4541f.png">

**Comment by Tbaut** [comment]
We should keep things consistent indeed, if it shows a point above.

**Comment by ltfschoen** [comment]
Closing as this is no longer an issue in the latest version
