### ISSUE TITLE
Warn users who enter a "To" address that matches the "From" address

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#252]
I created a transaction, but accidently entered the address that I was sending the transaction from as the value of the "To" address, I first realised my mistake when I went to Etherscan and saw "SELF" in blue https://kovan.etherscan.io/address/0x00c53e558609d0233a2965a8388286965dab31f5.
I think it would be helpful to add a tooltip warning the user that they're making a transaction where the From is the To address, which they wouldn't ordinarily do unless they want to waste their account balance on unnecessary transaction fees.

**Comment by amaurymartiny** [comment]
Closed by #255
