### ISSUE TITLE
"CHECKING..." freezes when enter amount less than 0.000000000000000001 on "Send THIBCoin" page

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#253]
I went to the "Send THIBCoin" page and have 4 Gwei selected by default. 
I wanted to see what the smallest amount of THIBCoin was that I could send.
But I found that after entering a recipient "Address" such as 0x004702bdcc3c7dbffd943136107e70b827028600, when I entered a value like 0.1 for "Amount" it triggers "CHECKING..." and changes back to "SEND". But if the "Amount" entered is less than 0.000000000000000001 (such as 0.0000000000000000009) it triggers "CHECKING..." but freezes and doesn't display "SEND" again, even if I reset all the input field values, so to get it to work again I have to click the "X" button to go back to the previous screen and then go back into the "Send THIBCoin" page again

<img width="353" alt="screen shot 2018-11-10 at 23 48 13" src="https://user-images.githubusercontent.com/6226175/48307003-e279c200-e543-11e8-8ea1-9aaf737529b6.png">

**Comment by yjkimjunior** [comment]
Hi @ltfschoen I followed the steps you outlined in the issue on the latest master but wasn't able to reproduce the issue. I took it a step further and added 6 more 0's but the send button still gets enabled after checking: http://recordit.co/uAMoGSFlgM

**Comment by Tbaut** [comment]
Closing as not reproducible. If this happen again, please open the console and show the eventual errors.
