### ISSUE TITLE
[UX] More granular denominations for ƒractional ETH amounts

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/fether#257]
It'd likely reduce the liklihood of human errors to have a toggle the amount display between plain decimals and intermediate denomination names, e.g. `0.000000000001` versus `1 szabo` / `1 microether`. And I think wallets in general need to start getting users used to the lingo of "Can you send me 12 finneys" rather than "Can you send me zero point zero zero zero .... zero ...  Eth?"

Unit | Wei Value | Wei
-- | -- | --
wei | 1 wei | 1
Kwei (babbage) | 1e3 wei | 1,000
Mwei (lovelace) | 1e6 wei | 1,000,000
Gwei (shannon) | 1e9 wei | 1,000,000,000
microether (szabo) | 1e12 wei | 1,000,000,000,000
milliether (finney) | 1e15 wei | 1,000,000,000,000,000
ether | 1e18 wei | 1,000,000,000,000,000,000

**Comment by yjkimjunior** [comment]
Or/also in the other direction E notation would be nice 

"1 Million is easier to write/read/check when written as 1e6 as in 1000000."

**Comment by Tbaut** [comment]
I'd be much more for the e notation that for the yet-another-name one. I personally don't like/use anything except Gwei, which is actually solely used for gas almost as its own currency.
I'd prioritize adding the equivalent in $ that is much more speaking to the users than anything else. https://github.com/paritytech/fether/issues/161

**Comment by yjkimjunior** [comment]
Closing in favor of #161
