### ISSUE TITLE
Design brainstorming - account screen

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#264]
We need to finds ways to organize better our menus to allow the amount of options to scale.
Here are some ideas:
![image](https://user-images.githubusercontent.com/33178835/48869252-d65ff100-eddc-11e8-9b52-9247baa55405.png)

Keeping "add token" in a corner and "save account keystore as JSON" in another, is not pleasant esthetically.
What do you think @axelchalon @amaurymartiny @yjkimjunior ?

**Comment by yjkimjunior** [comment]
Mucking around a bit and ended up sort of merging the two options into one.

For (1), it seems we are taking the two main actions and burying them in a dropdown. 
For (2), I agree with you that splitting up the options is not ideal and also that after ~4 tokens get added the Add Token button gets buried at the bottom. 

So my merged proposal is to leave the two main actions to be persistently visible, and use the dropdown for any secondary things, so we use all corners of the screen and clearly separate primary and secondary actions.

what do you think? @Tbaut @amaurymartiny @axelchalon 

![fether accounts](https://user-images.githubusercontent.com/10432070/48874802-fde99600-eda9-11e8-875f-e4e80589fab8.png)

**Comment by Tbaut** [comment]
The more I think about it, the less I like the version 2. My idea was to make the "add token" more natural, at the end of the list, but you're right, the implementation part isn't ideal.

We call them primary because we have nothing else, I think both "add token" and "backup account" are secondary actions though because you basically do it once, and almost never do it again. I wouldn't see a problem to hide them away. Also because they are so different and unrelated, I don't see why these 2 would be grouped together, and other options would be in the other corner.

Having them both at the bottom (and nothing in the top right hand corner) is quick and cheap way to do it for now, but it doesn't scale. 

Users like our design right now because it slick, adding buttons here and there breaks it IMO, I'd like to avoid having all corners with a different buttons.

**Comment by Tbaut** [comment]
I actually see a pattern that we *could* use on the account list view also, 2 variants to make the workflow more straight forward:
![image](https://user-images.githubusercontent.com/33178835/48896410-da752880-ee47-11e8-9dc6-04e305531312.png)

**Comment by amaurymartiny** [comment]
code-related: if/when this is done, it would be perfect to split [this component](https://github.com/paritytech/fether/blob/94f2db7a920ddd15cc42db04d331d460836b438e/packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js) into smaller components.

**Comment by Tbaut** [comment]
Yup, one view per type of import should be the goal. It'd look much simpler for users spliting the current component in 3 different components.

**Comment by Tbaut** [comment]
Closing in favor of https://github.com/paritytech/fether/issues/389
