### ISSUE TITLE
Use an up to date token currated list

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#267]
Our Token registry is outdated, it doesn't have any interface anymore and users can't easily add/edit/remove tokens (e.g DAI isn't part of the list).

We need to move to something else for mainnet release.

As mentioned [here](https://github.com/paritytech/fether/issues/6#issuecomment-389797152) I suggest to use https://github.com/ethereum-lists/tokens/ that is an open source manually curated token registry by users

**Comment by amaurymartiny** [comment]
Most of them, even on main, don't have images. That was one reason why I chose our registry that time.

**Comment by Tbaut** [comment]
That's too bad, we'll need to have a nice default icon.
I'd still foster token availability (and validity) over nice design. Our registry is barely used afaik.

**Comment by Tbaut** [comment]
Here are different implementations, also with IPFS
- Trezor https://github.com/trezor/trezor-common/blob/078cf07658a99888adca19e3284864a5354da550/ethereum_tokens-gen.py
- MyCrypto https://github.com/MyCryptoHQ/MyCrypto/blob/3074e50909495d171edff2ec63a3e30bbeeb335a/scripts/update-tokens.ts
