### ISSUE TITLE
Need a constant screen size especially when loading an account's tokens

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/fether#275]
The screen size changes as I'm about to click on items on the bottom nav if there are more than a couple tokens to load, then reaches a fixed limit and switches to a scroll view. 

It should be constant throughout the entire app as much as possible to avoid annoying instances of trying to click an element and it moves and user ends up clicking something else. 

** this happens within the same account, but the screenshots use different accounts as this is hard to screenshot. 

## Starts as
![screen shot 2018-11-27 at 3 18 36 pm](https://user-images.githubusercontent.com/10432070/49118047-bfdfec80-f257-11e8-8a08-9c162a934ce7.png)

## Loads more tokens and screen size changes
![screen shot 2018-11-27 at 3 18 30 pm](https://user-images.githubusercontent.com/10432070/49118046-bf475600-f257-11e8-840d-efd273d7b4d4.png)

Lots of rage if trying to click on `Backup Tokens` for example and accidentally end up click one of delayed loaded tokens instead.

**Comment by Tbaut** [comment]
Agreed, that's annoying, It happened to me too, thanks for the issue :)
