### ISSUE TITLE
Estimated Gas Limit when Sending THIBCoin is variable

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#295]
**Is the following behaviour expected?:**

Similar to #294 when in **Send THIBCoin** and you're debugging the same way with the same user who has 0.000063000000000001 ETH and a THIBCoin balance of 0.0055. If you start with a transaction amount of 0.000000000000000001 then the Estimated Gas Limit is 39401.25 (i.e. Estimated gas 31521, with buffer 39401.25)  (it differs from just sending Ether since we have to allow for costs associated with interacting with the token contract, then if you increase the amount to be sent up to 0.0055 then the Estimated Gas Limit increases to 39801.25 (i.e. Estimated gas 31841, with buffer 39801.25)

**The following works as expected:**

When you increase the amount of TIB that you want to send to 0.00551 (i.e. above your available TIB account balance) then the Estimated Gas Limit is 0 and it gives tooltip "You don't have enough TIB balance", which is expected since they have insufficient tokens to send.

Note that it always correctly gives message "You don't have enough ETH balance" because the Estimated Transaction Fee is 0.00011940375 ETH, which is larger than their account balance of 0.000063000000000001 ETH, whereas the Estimated Transaction Fee is only 0.000063 ETH when sending ETH instead of another token that needs to accommodate extra costs for interacting with the token contract).

**Comment by Tbaut** [comment]
This is expected for multiple reasons:
- Basic transaction cost depends on how many 0s you have in a data field.
- The contract state could change in the meantime, so you might be zeroing or unzeroing some sstore entries.

copyright @tomusdrw  :)
