### ISSUE TITLE
Change font size of amount to be send when over 9 digits are entered

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#308]
I have an account with THIBCoin, and I've been asked to transfer all of it to another account to cover the cost of a ransom or face consequences.
In the UI I go to the "Send THIBCoin" page where it shows I only have a balance of 1,123.460,932.
I know this transaction has to be precise, but luckily I'm a long-term user so I know the values shown on this page in UI are rounded to 6 decimal places, so to make sure I enter the correct value I click the link provided by https://github.com/paritytech/fether/issues/98 (instead of having to use a search engine or bookmark to find the etherscan link where I get can the exact account balance that has been demanded (note that the value shown on Etherscan is the base units https://kovan.etherscan.io/token/0x4a6e6c3868a279e1d9047b42c3fb356ff4680003?a=0x005072Fb985cc64d8A1Ce00ECe26279f73c12F8a.
So I enter the exact account balance, which is actually 1,123.460,932,110 THIB.

<img width="354" alt="screen shot 2018-12-19 at 6 17 22 pm" src="https://user-images.githubusercontent.com/6226175/50229077-87e14a80-03ba-11e9-8754-b34566bb419c.png">

But it clips the value as shown above.

So propose to reduce the font-size when the value entered is >9 digits long. This involves changing 
the CSS `input.form_field_amount[type='number'] from its existing font-size: 2.98598rem;

If we reduce it to font size of 2rem it fits 14 decimal places, or if we reduce it to 1.4rem it fits the smallest unit.

<img width="357" alt="screen shot 2018-12-19 at 6 23 21 pm" src="https://user-images.githubusercontent.com/6226175/50229382-41402000-03bb-11e9-88b5-75c4463d5d08.png">

Alternative is to permanently reduce the font size to some value.

**Comment by axelchalon** [comment]
Sounds good, maybe a library like https://github.com/rikschennink/fitty could help, we could then make the text automatically shrink to fit its container without clipping

**Comment by Tbaut** [comment]
Totally, I was thinking about it the other day. Doing it dynamically would be great. I guess it's fine to check for the amount of digits or catch the `overflow` event.
