### ISSUE TITLE
Switch to an open source block explorer with less trackers

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#311]
I suggest to redirect our users to [Blockscout](https://blockscout.com/eth/kovan) instead of Etherscan, it's nice, open source, built by our friends at POA network, although the website itself is quite slow (friendly ping @igorbarinov) and using google analytics (Matomo would have been great, I opened and issue on their side https://github.com/poanetwork/blockscout/issues/1274). The need to move from Etherscan also because of disqus, the threats are explained [here](https://slideslive.com/38911970/plugging-the-metadata-leaks-in-the-ethereum-ecosystem).

**Comment by amaurymartiny** [comment]
Closed in #314
