### ISSUE TITLE
Prompt users for a new releases with a link (update Fether)

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#313]
Self explanatory. Also if a security release of Parity Ethereum is out, we need some way to tell users.
Not so cool: it's centralized on us, just like our binaries.

**Comment by axelchalon** [comment]
We could also detect the new Parity Ethereum release automatically, download it and run it (assuming compatibility with Fether). I don't think a manual action from the user is necessary.

**Comment by Tbaut** [comment]
I'm on the fence considering auto-update and the threat that it represents regarding the security and the fact that a Parity Ethereum release might very well break some Fether functionalities. It happened not too long ago with a minor problem (where the node wasn't exited properly). This is also the reason I opened #204 for us to control what Parity Ethereum version comes with Fether.

**Comment by amaurymartiny** [comment]
I agree with #204, and I would say we fix 1 version of parity-ethereum into 1 version of Fether, i.e. no possibility to update parity-ethereum without updating Fether.

So if PE has a major update, we update Fether asap, and prompt the user inside Fether to update Fether.

**Comment by amaurymartiny** [comment]
Looks good for the first 2 screens (maybe a small wording change). However I'm not sure steps 3 and 4 are technically doable. I haven't looked at Electron's self-updaters, but I'm assuming at one point, Fether needs to be closed and re-launched to update to the latest version.

**Comment by Tbaut** [comment]
Wording and presentation's suggestion ![image](https://user-images.githubusercontent.com/33178835/50616577-53f14380-0ee9-11e9-8900-49ce4e18b556.png)

**Comment by axelchalon** [comment]
We might want to look into this https://electronjs.org/docs/api/auto-updater / https://electronjs.org/docs/tutorial/updates

**Comment by Tbaut** [comment]
It's up to the one that picks this issue, but just having a link for the user to manually update is already better than nothing :)

**Comment by axelchalon** [comment]
Agreed, we can implement this incrementally.

A first could be to periodically check https://api.github.com/repos/paritytech/fether/releases/latest and compare against the current version of Fether. If there's a newer version, display a modal with a link to the GH releases page. (would be slightly more complicated if we have two release tracks, i.e. stable & beta)

**Comment by Tbaut** [comment]
>would be slightly more complicated if we have two release tracks, i.e. stable & beta, but I don't think it's the case

won't be the case in the short term, but having an extra check for beta/stable would be cool.

**Comment by amaurymartiny** [comment]
I think it's doable: there's a `target_commitish` field in Axel's link, which should be beta or stable. Worst case scenario, if we keep the current release tagging convention `v*.*.*-(stable|beta)`, then we can also check for new versions.
