### ISSUE TITLE
Add a scientific notation toggle button. Show non-scientific notation equivalent.

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#316]
Propose a scientific notation toggle button to be positioned near the ['Max' toggle button](https://github.com/paritytech/fether/pull/302).

By default the scientific notation button would be turned 'off' and users will be prevented from entering the following characters `+-eE` in the 'Amount' input field when in the 'Send Ether' or 'Send THIBCoin' pages.

However if they toggle the scientific notation button 'on', then we'll allow them to enter those characters. Also when it's toggled 'on', we'll shown the non-scientific equivalent value to the user (i.e. if they enter `1e-3` then we'll show it's equivalent somewhere on the screen, or the user can just check its equivalent in the 'Details' section https://github.com/paritytech/fether/pull/307)

A benefit is to make it obvious to users that they can enter values in scientific notation more obvious.

See related comment: https://github.com/paritytech/fether/issues/247#issuecomment-448944761.

**Comment by Tbaut** [comment]
I think it's not needed to add such a button, I'm not in favour of showing scientific notation either. We should think about non scientific users, this is not something we are used to see in everyday life and I don't think it should be implemented.
