### ISSUE TITLE
Password shown in plain text in Developer Tools Console when entered incorrectly

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#317]
When I'm prompted to enter my password to send a transaction but I enter the incorrect password (i.e. `myincorrectpassword`), when I click 'Send' it displays my password in plain text in the Developer Tools Console error message as shown below:

```
index.js:1452 signer_confirmRequest(["0x2",{},"myincorrectpassword"]): -32021: Account password is invalid or account does not exist.
```

**Comment by amaurymartiny** [comment]
upstream https://github.com/paritytech/js-libs/issues/77

**Comment by ltfschoen** [comment]
Using the latest master branch it now displays:
```
index.js:1452 signer_confirmRequest(["0x1",{},"***"]): -32021: Account password is invalid or account does not exist.
```
