### ISSUE TITLE
currentBlock.minus(...).mul is not a function

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/fether#325]
On branch master, after 30 seconds or so the app crashes with unhandled TypeError in `withHealth.js:97`. Maybe a result of a breaking change to `syncStatus` from light.js? 

![screen shot 2018-12-26 at 12 56 24 pm](https://user-images.githubusercontent.com/10432070/50432616-0899cc80-090e-11e9-9001-0114dded6a60.png)

**Comment by amaurymartiny** [comment]
Could you describe how you fixed it? Just in case someone else finds this thread
