### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#329]
When I try to create a new account by clicking the "+" icon on the account list screen, then entering an account name and pressing "Next", then I'm prompted to write down the account phrase that's shown. But if I have Developer Tools open at this point, as soon as I press "Next" it shows the following warning:

<img width="773" alt="screen shot 2019-01-03 at 11 14 11 am" src="https://user-images.githubusercontent.com/6226175/50618701-b3cb0700-0f48-11e9-9acd-4c00c98eb173.png">

**Comment by amaurymartiny** [comment]
I got this too.
