### ISSUE TITLE
Account is created after entering matching password confirmation but before confirming to create the account

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#330]
When creating an account, once I get up to the screen shown in the below screenshot, as soon as I enter a value for the "Confirm" that matches the value of "Password" the "CONFIRM ACCOUNT CREATION" button is enabled (instead of disabled), but instead I clicked the "BACK" button, which returned me to the account list screen where I found the new "test6" account was actually listed (even though I didn't confirm that I wanted to create the account).

I expected the "BACK" button on that page to always take me back to the previous pages (i.e. which would be useful if I were a user who perhaps had previously entered the recovery phrase to confirm that they'd written it down on paper, but then somehow then suddenly forgot what it was or the piece of paper flew out the window and they wanted to go back two pages to where it was shown again). 

However the "BACK" button only exhibits the functionality of going back to the previous page if a value hasn't been entered into the "Password" or "Confirm" input fields, or if the values in both those fields don't match.

When both "Password" and "Confirm" input field values match and you then click the "BACK" button it actually appears to perform the same functionality as clicking the "CONFIRM ACCOUNT CREATION" button, and in the Developer Tools console both actions cause it to display `fether-react:createAccountStore Saving account to Parity.`

I expected clicking the "BACK" button even after entering matching "Password" and "Confirm" input field values to still take me back to the previous screen.

Also it wasn't immediately clear to me that the "<--" arrow at the top performs the equivalent of a "CANCEL" button anytime during the new account creation. For example if you enter matching "Password" and "Confirm" input field values and then click that arrow, it returns to the account list screen but doesn't create the account, as expected.

So initially I was confused as to why it created an account before I confirmed that I wanted one created, and then I was curious to see whether any password had been associated with the account even though I didn't confirm account creation. So I clicked the "test6" account and then clicked "Backup account", and I found that the password that I had previously entered in the "Password" and "Confirm" input fields was the one that had been associated with the account as it was the only one that allowed me to unlock the account to download the JSON keystore file

<img width="356" alt="screen shot 2019-01-03 at 2 36 33 pm" src="https://user-images.githubusercontent.com/6226175/50622899-0aded500-0f65-11e9-8888-0b50c67067a1.png">

**Comment by Tbaut** [comment]
Ho pretty bad bug! It's fixed by https://github.com/paritytech/fether/pull/323

**Comment by Tbaut** [comment]
solved https://github.com/paritytech/fether/pull/323
