### ISSUE TITLE
Details view closes and reopens on amount/address change

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#334]
Following the merge of #293 when the "Transaction details" view is open, changing the amount results in a unaesthetic close and open of the details view.

It think we could allow users to click "Details" even if the transaction is incomplete. We would simply show blank fields. Also a couple working change suggestions to keep things a little simpler:

![image](https://user-images.githubusercontent.com/33178835/50741104-ec910780-11f8-11e9-8d6b-666e418950b4.png)

**Comment by ltfschoen** [comment]
Yes, or perhaps show some kind of animated loading icon or similar in the Transaction Details section?

**Comment by Tbaut** [comment]
The only Problem I see with an animation is that it give the idea that something is happening in the background, whereas it's not the case. We should either find a nice way to say "transaction not complete yet" without resizing the field, or hide the obsolete data. I'll give it a shot.
