### ISSUE TITLE
Short address on account screen and full address on transfer recap screen

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#337]
I think that we give too much importance to the account full address at the wrong place.
The address is shown in full on the account screen, but not on the transaction recap (!). Also the identicon is very small which doesn't look great for Signer accounts. 
What I propose:

- **Account view**:
We use the same presentation as the account list, short address, big identicon, and keep the address clickable to copy it.
![image](https://user-images.githubusercontent.com/33178835/50770703-848a0200-1288-11e9-86cb-4f880cd99ec8.png)

- **Transaction recap**:
We show the account with the identicon and the full address (today we have a useless account balance card):
![image](https://user-images.githubusercontent.com/33178835/50771101-e6973700-1289-11e9-84ec-3efbc3b7db68.png)

**Comment by ltfschoen** [comment]
I'd also love to see a solution to not having to see the value of the 'To' field wrap around onto the next line that doesn't involve making it unreadable

**Comment by ltfschoen** [comment]
For the short address that's clickable, we could animate a transition to display its full address on hover, and on blur animate a transition back to the short address

**Comment by ltfschoen** [comment]
@Tbaut On your proposed "Transaction recap" screen you've removed showing the available account balance of the token that the user wants to send, so they'd always have to remember what their available account balance is before they click a token to go to its "Send <TOKEN_NAME>" page, or alternatively they'd have to press the "MAX" button to remind themselves.

**Comment by ltfschoen** [comment]
@Tbaut Sorry my mistake, I re-read it again, the  "Transaction recap" screen is the Unlock component screen where the user just enters their password (not the TxForm screen as I thought)

**Comment by Tbaut** [comment]
Fixed :tada:
