### ISSUE TITLE
Unhandled Rejection (Error): Unable to estimate gas, when trying to send transaction with bad connectivity

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#354]
I was on the "Send Ether" page with a bad internet connection, so the "Bad connectivity" modal kept appearing.
After entering an amount and recipient, then clicking the "Details" button, the page would refresh.
Then I tried entering an amount and recipient and clicked the "Send" button, but it displayed the following in the Fether window.

```
Unhandled Rejection (Error): Unable to estimate gas

src/paritytech/fether/packages/fether-react/src/Send/TxForm/TxForm.js:56
  53 | field: /to|amount/, // when the value of these fields change...
  54 | updates: {
  55 |   // ...set field "gas"
> 56 |   gas: async (value, allValues) => {
     | ^  57 |     const { parityStore, token } = this.props;
  58 |     let newGasEstimate = null;
  59 | 
View compiled
▶ 5 stack frames were collapsed.
```

And the following in Dev Tools Console:

<img width="1135" alt="screen shot 2019-01-12 at 12 43 37 pm" src="https://user-images.githubusercontent.com/6226175/51067656-5a5d8900-1668-11e9-93df-413f66309694.png">

**Comment by ltfschoen** [comment]
I just tried doing the same thing, sending an amount from a Parity Signer account with a valid value and recipient. But it displayed the following in the Fether window:

```
TypeError: Cannot read property 'toNumber' of null

getEthereumTx
src/paritytech/fether/packages/fether-react/src/utils/transaction.js:133
  130 | 
  131 | const txParams = {
  132 |   nonce: '0x' + transactionCount.toNumber().toString(16),
> 133 |   gasLimit: '0x' + gas.toNumber().toString(16),
      | ^  134 |   gasPrice,
  135 |   chainId
  136 | };
View compiled
transactionToRlp
src/paritytech/fether/packages/fether-react/src/utils/transaction.js:192
  189 |  * From https://git.io/fh3Sd
  190 |  */
  191 | export const transactionToRlp = thisTx => {
> 192 |   const tx = getEthereumTx(thisTx);
  193 | 
  194 |   const { v, r, s } = tx;
  195 | 
View compiled
SendStore.getRlp
src/paritytech/fether/packages/fether-react/src/stores/sendStore.js:112
  109 |  * Get the RLP of an (unsigned) transaction.
  110 |  */
  111 | getRlp = () => {
> 112 |   return transactionToRlp(this.tx);
      | ^  113 | };
  114 | 
  115 | /**
View compiled
TxQrCode.render
src/paritytech/fether/packages/fether-react/src/Send/TxQrCode/TxQrCode.js:69
  66 |     scan={false}
  67 |     onScan={() => {}}
  68 |     account={address}
> 69 |     rlp={getRlp()}
     | ^  70 |   />
  71 | </Card>
  72 | <nav className='form-nav -binary'>
View compiled
▶ 39 stack frames were collapsed.
```

<img width="1135" alt="screen shot 2019-01-12 at 12 52 20 pm" src="https://user-images.githubusercontent.com/6226175/51067779-5a11bd80-1669-11e9-8051-75901a6cb593.png">

<img width="773" alt="screen shot 2019-01-12 at 12 54 10 pm" src="https://user-images.githubusercontent.com/6226175/51067785-744b9b80-1669-11e9-9a9b-f72deb440d2d.png">

**Comment by ltfschoen** [comment]
Perhaps unrelated but shortly afterward I got this and did what it said

<img width="361" alt="screen shot 2019-01-12 at 1 02 32 pm" src="https://user-images.githubusercontent.com/6226175/51068354-f25f7080-1670-11e9-829f-cd3577c9c1fc.png">

**Comment by axelchalon** [comment]
It looks like this happened to you in the Parity Signer branch (also happened to me a couple of times); can you repro on master?

**Comment by ltfschoen** [comment]
Yes you're correct, sorry forgot to specify the branch was ' ac-signer' of the PR https://github.com/paritytech/fether/pull/336.

I tried to reproduce the error, but I can't.

I was able to reproduce the issue with the 'Details' button. Whenever I try and click 'Details' it just resets the 'Send Ether' page now.

**Comment by ltfschoen** [comment]
I can't reproduce the bug with the "Details" button anymore.
