### ISSUE TITLE
Synchronisation continues even after kill the Fether generated Parity Ethereum Light database

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#358]
On macOS, if I run Fether **without** a separate Parity Ethereum instance running on Kovan, then Fether automatically creates a Parity Ethereum instance with the chain database in ~/Library/Application Support/io.parity.ethereum/chains_light/kovan and synchronises.

If I have Parity Ethereum and then delete the Kovan Light chain database directory contents ~/Library/Application Support/io.parity.ethereum/chains_light/kovan/db

Then in the terminal it keeps synchronising blocks and in the UI it still saying "Synced (kovan)"

Even though though this subdirectory no longer exists: ~/Library/Application Support/io.parity.ethereum/chains_light/kovan/db

Whereas if I start a **with** a separate Parity Ethereum instance running on Kovan with:
```
./target/release/parity --chain kovan --light
```

Then it shows my DB path ~/Library/Application Support/io.parity.ethereum/chains_light/kovan/db/9bf388941c25ea98

If I then delete the Kovan Light chain database directory contents ~/Library/Application Support/io.parity.ethereum/chains_light/kovan/db

Then in the terminal where I started the Parity Ethereum node it panics (as expected).
```
...
Thread 'Verifier #4' panicked at 'Database flush failed: IO error: While open a file for appending: ~/Library/Application Support/io.parity.ethereum/chains_light/kovan/db/9bf388941c25ea98/overlayrecent/db/003476.log: No such file or directory. Check disk health and space.', ethcore/light/src/client/mod.rs:341
...
Thread 'main' panicked at 'Propagating verifier thread panic on shutdown: Any', libcore/result.rs:1009
```
And in the UI it says "Connecting to the node..." (as expected)

### Questions

1) **If we run Fether **without** a separate Parity Ethereum then when we kill the Parity Ethereum Light database directory, shouldn't it immediately display "Connecting to the node..."?**

2) **Why don't we show the DB path of the Parity Ethereum instance that's generated by Fether in the Fether logs?**

3) **How can I purge a Light database (i.e. in the 'chains_light' subdirectory instead of the 'chains' directory) from the Parity Ethereum CLI?** I want it to purge the Light database that's stored in ~/Library/Application Support/io.parity.ethereum/chains_light/kovan, but if I run the following it purges the database in ~/Library/Application Support/io.parity.ethereum/chains/kovan

```
./target/release/parity --chain kovan db
```

**Comment by axelchalon** [comment]
> How can I purge a Light database (i.e. in the 'chains_light' subdirectory instead of the 'chains' directory) from the Parity Ethereum CLI?

`./target/release/parity --light --chain=kovan db kill`

**Comment by Tbaut** [comment]
>If we run Fether without a separate Parity Ethereum then when we kill the Parity Ethereum Light database directory, shouldn't it immediately display "Connecting to the node..."?

Because the RPC connection is still live.
>Why don't we show the DB path of the Parity Ethereum instance that's generated by Fether in the Fether logs?

We could. But by messing up with the low level files, I'm not surprised it breaks :rofl: . I don't think we should spend time on this. Please close the issue if your questions are answered.

**Comment by ltfschoen** [comment]
Closing the issue based on comments
