### ISSUE TITLE
TypeError: Cannot read property 'toNumber' of null when click "Scan" to send transaction from Parity Signer account

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#361]
I just tried using the latest 'master' branch with `yarn; yarn start` to send a transaction with some ETH from a Parity Signer account that I had imported. When I clicked the "Scan" button it displayed the following error message.

And when I restarted Fether I then did the same steps (but ran `yarn; yarn build; yarn start`), when I clicked the "Scan" button it worked and opened the QR page without the error. 

<img width="1350" alt="screen shot 2019-01-16 at 11 59 17 am" src="https://user-images.githubusercontent.com/6226175/51220578-e41f9600-1989-11e9-934b-2db3ff73f603.png">

<img width="984" alt="screen shot 2019-01-16 at 11 59 34 am" src="https://user-images.githubusercontent.com/6226175/51220589-eaae0d80-1989-11e9-93ab-d64235e1df0d.png">

<img width="362" alt="screen shot 2019-01-16 at 12 21 54 pm" src="https://user-images.githubusercontent.com/6226175/51220594-ee419480-1989-11e9-8838-92a50947ed4b.png">

EDIT: 
Regarding the padding around the Electron frame, I think I must have accidentally changed the zoom level of the Electron app, so I just fixed it by going to View > Actual

**Comment by ltfschoen** [comment]
It may be because the macOS FaceTime HD Webcam has issues, because after I clicked "Next Step" after scanning the QR code with Parity Signer, my webcam wasn't working

<img width="358" alt="screen shot 2019-01-16 at 12 28 59 pm" src="https://user-images.githubusercontent.com/6226175/51220725-86d81480-198a-11e9-8a68-f622ed0e3fe6.png">

So I may need to restart my computer.

**Comment by axelchalon** [comment]
I also had this issue, don't think it's related to the webcam. I think it's related to gasPrice somehow not being defined in the values submitted by the form.

**Comment by ltfschoen** [comment]
> I also had this issue, don't think it's related to the webcam. I think it's related to gas/gasPrice somehow not being defined in the values submitted by TxForm.

Agreed. I was just able to replicate the same issue multiple times just by completing the TxForm page too quickly. i.e. pasting a recipient, entering a value, and pressing the "Scan" button **as soon as the scan button appeared**

**Comment by ltfschoen** [comment]
And the reason why I was probably prompted to "Reload" was because Kovan seems to have issues and the transaction still says "Pending" on Etherscan even after waiting for about 5-10 mins today

**Comment by ltfschoen** [comment]
It happens when sending a transaction from a non-Parity Signer account too

**Comment by ltfschoen** [comment]
I've discovered that it's caused when it lets you click "Send" when in the "Transaction Details" section still says "Missing input fields...".
So to replicate, go to the "Send Ether" page, click the "Details" button, paste a recipient address, and enter an amount. Keep changing the amount value and wait each time you do to see if it still says "Missing input fields..." after it has already changed to "Send". If you click "Send" at this stage it will display the error page, but if you wait until it's calculated and shown the transaction details it won't error

**Comment by ltfschoen** [comment]
It appears to be Parity Signer-specific, it seems that when you click "Scan" it tries to go to the paritytech/fether/packages/fether-react/src/Send/TxQrCode/TxQrCode.js, where it calls `getRlp()` to get teh value for the rlp prop of the QrSigner component, which calls `transactionToRlp(this.tx)` to get the RLP of the unsigned tx that is provided as an argument paritytech/fether/packages/fether-react/src/stores/sendStore.js, but it crashes if `this.tx` contains a `gas` property that's undefined.
So we need to prevent the user from clicking "Scan" before the `gas` property has been determined

**Comment by axelchalon** [comment]
I investigated as well and what I got was:
- The form is valid (validateForm) when `!estimatedTxFee`.
- `!estimatedTxFee` when no amount/gas/gasPrice
- gas is set **asynchronously** when amount/to changes
- if amount/to changes and validateForm is called before gas is set, then we can send the form (deemed valid) without gas (in other terms: if fetching the gas takes more time than the 1s debounce)

This can be reproduced by changing the line with:
```js
newGasEstimate = await estimateGas(
              allValues,
              token,
              parityStore.api
            ).then(x => 
              new Promise((resolve,reject) => {
                setTimeout(() => {resolve(x)}, 15000);
              })
            );
```

This only triggers an error for Parity Signer accounts, but for node accounts it means that the gas isn't sent with the transaction, which isn't intended either.
