### ISSUE TITLE
Make the T&C's take the full screen

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#366]
The T&Cs screen looks shrunk right now, we should make sure to have it full screen, or to reduce the ~~screen~~ window size.
![image](https://user-images.githubusercontent.com/33178835/51281497-d8ac8900-19e2-11e9-978d-9ab91f0ca41a.png)

**Comment by ltfschoen** [comment]
@Tbaut I'm not sure what you mean by "full screen"... do you mean maximise the whole Electron window so it takes up the users entire screen just for the T&Cs page? What do you mean by "reduce the screen size"?

**Comment by Tbaut** [comment]
I updated the image. If you see the T&Cs, you'll understand right away, the orange part highlighted in the first post should be either filled, or removed. Either we expand the T&Cs block, or we reduce the window size. Lmk if that's not clear.

**Comment by ltfschoen** [comment]
Ok, sorry when I run Fether on the T&C screen it doesn't show the section that you've shown in orange, it just automatically resizes the Electron window
