### ISSUE TITLE
Prevent clicking on any link or button when a menu is open

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#383]
When the popup menu is open, the user shouldn't be able to click on any menu.
It looks like this behaviour reappeared.
cf https://github.com/paritytech/fether/pull/318#issuecomment-449424025 and https://github.com/paritytech/fether/pull/356#issuecomment-454010067

**Comment by ltfschoen** [comment]
It was because I removed this logic https://github.com/paritytech/fether/pull/356/commits/e122b380ced1f9d244f890bc09dfdd902727c00c#r248668150
