### ISSUE TITLE
Dynamic card layout on Account List

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#387]
Currently on the account list page we have a lot of white space on the right-side of each Account because we're now using short addresses and it's just being displayed as a vertical list as shown below.

<img width="357" alt="screen shot 2019-01-23 at 10 55 58 am" src="https://user-images.githubusercontent.com/6226175/51573454-7e895780-1efd-11e9-8490-72b11a6fa570.png">

Could use use Flexbox and display it in tiled format as shown below? Or even add this option to the Settings menu?

<img width="361" alt="screen shot 2019-01-23 at 10 52 36 am" src="https://user-images.githubusercontent.com/6226175/51573557-f48dbe80-1efd-11e9-9b20-a518b3c1977e.png">

Since we don't have a restriction on name length we should shorten the name to fit the component, that way it would show consistently sized tiles and spacing in the screenshot above. My account with a really long name also doesn't fit on the Account page as shown below:

<img width="362" alt="screen shot 2019-01-23 at 11 00 20 am" src="https://user-images.githubusercontent.com/6226175/51573612-33bc0f80-1efe-11e9-8507-9facf0e88e3b.png">

**Comment by ltfschoen** [comment]
If we only display the first 8 chars of its name on the Account List page, and the first 25 chars of its name on the Account page, then it looks nicer, as shown below:

<img width="361" alt="screen shot 2019-01-23 at 11 16 35 am" src="https://user-images.githubusercontent.com/6226175/51574143-be9e0980-1f00-11e9-80d6-fc9220b5cead.png">

<img width="361" alt="screen shot 2019-01-23 at 11 16 59 am" src="https://user-images.githubusercontent.com/6226175/51574147-c1006380-1f00-11e9-91ef-eaae0826d5ee.png">

**Comment by Tbaut** [comment]
I'm not a fan of those tiles, this makes things small and shrunk. I like having spaces and our users like the lightweight design too, let's try to keep it that way.

The last screenshot is interesting, this is a case I tested before and I did not have the problem mentioned with the title on top of the buttons, so I didn't mention it:
![image](https://user-images.githubusercontent.com/33178835/51598006-e9865e80-1efc-11e9-8c71-b11d5a0ff33f.png)


>Also, would it be good to have an input field to search for an account name/address and filters the list to just show that account?

I don't think this is a problem at the moment. We can tackle it if it comes up later but i wouldn't spend time on this now.

**Comment by Tbaut** [comment]
It'd be a quite big change in Fether's visual identity that would need to be validated by proper user feedback. 

We don't know what's the average amount of accounts right now. Let's not try to find solution to problems that don't exist yet.

>Also, are we going to address the UI issue of users with really long names? If so do you have any preference?

I do not have the problem right now, cf my screenshot on master (not awesome looking, but not broken). Your latest screenshot looks good IMO. We should also consider limiting the amount of characters then in the name.

>In Fether will we allow users to choose different colour themes (i.e. colour picker palette), or toggle between different common layouts (i.e. list vs tiled view)?

Sure why not, like a dark mode. Not a priority for now but considering the amount of websites and apps that propose such a mode, it's surely popular.

**Comment by Tbaut** [comment]
Closing as the question is answered.
