### ISSUE TITLE
Can not add token by contract

### ISSUE THREAD

**Issue by xhipster** [paritytech/fether#395]
User story: 

I cannot find my token [CBD] nor by ticker nor by contract 0x136c1121f21c29415D8cd71F8Bb140C7fF187033 nor by name

**Comment by amaurymartiny** [comment]
Hey @xhipster! There is currently no (easy) way to add a token, we're using our own registry of tokens, and it might not be up-to-date. We're planning on #267, which should make this possible, so I'll close this issue for now and mark as duplicate.

Do note that Fether is only on Kovan testnet right now, so are you sure your token is on kovan too?

If you really need to see your token inside Fether asap, please re-open the issue, and we can guide you on how to add it.
