### ISSUE TITLE
Checksum mismatch, expecting X, got Y, when building binary on macOS

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#397]
These are the steps I followed to encounter the issue when trying to build a binary on macOS

*  Obtained a Github Token from Github and added it to my ~/.bash_profile `export GH_TOKEN="XYZ"`
* Fetched and checkout a remote branch to build its binary .dmg file

```
git fetch origin luke-branch-1: luke-branch-1;
git checkout luke-branch-1;
```

* Install dependencies, build release for macOS

```
yarn; yarn build; yarn release --mac;
```

* Kill and remove previous installation of Fether

```
rm -rf /Applications/Parity\ Fether.app/
```

* Open folder containing built binary .dmg file and run it

```
open ./packages/fether-electron/dist/Parity\ Fether-0.3.0.dmg
```

* Drag "Parity Fether.app" into Applications folder and wait for it to transfer it ~1Gb

* Run Fether

```
open /Applications/Parity\ Fether.app/
```

* Encounter checksum mismatch issue when it got had downloaded 100% of Parity Ethereum using Fether

<img width="408" alt="screen shot 2019-01-31 at 12 26 19 am" src="https://user-images.githubusercontent.com/6226175/51985124-3d8ed580-24f1-11e9-95ee-38bc83e683be.png">

* Note that Parity 2.3.0-beta has checksums as follows:
<img width="609" alt="screen shot 2019-01-31 at 12 27 37 am" src="https://user-images.githubusercontent.com/6226175/51985522-2bf9fd80-24f2-11e9-8480-d7fb62d3fc38.png">

So it had downloaded the following from the Parity Vanity service

<img width="827" alt="screen shot 2019-01-31 at 12 23 25 am" src="https://user-images.githubusercontent.com/6226175/51985611-61065000-24f2-11e9-86b9-d7972d3bbbc3.png">

But the checksum that it is **expected** cannot be found at https://vanity-service.parity.io/parity-binaries, only the **got** version value that was downloaded is correct 

Note: Relates to discussion in "Simply Fether" Riot channel on 16 Jan by Thibaut where it was pointed out that this issue is because the Vanity server needed reseting since it was comparing against **cached** values. It needs https://github.com/paritytech/fether/issues/313 and https://github.com/paritytech/fether/issues/204 to be resolvec

**Comment by amaurymartiny** [comment]
It's a cache issue, but it may be happening on the CDN level. The same URL for me shows a different cache value than yours:

<img width="792" alt="screenshot 2019-01-30 at 15 10 48" src="https://user-images.githubusercontent.com/1293565/51986868-7bfca400-24a1-11e9-95fc-cdefc2713adc.png">

(btw, the binaries you screenshoted for 2.3.0 are for beta, and we're using stable in Fether)

**Comment by amaurymartiny** [comment]
I would propose to close this issue, since it's out of scope of fether. Let's focus on #204 (which Axel is working on).
