### ISSUE TITLE
Add Fether menu item to toggle between Enable/Disable Always On Top and save the setting

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#413]
Add a new menu item in the Window tab called "Enable Always On Top" that when selected calls `setAlwaysOnTop` https://electronjs.org/docs/api/browser-window#winsetalwaysontopflag-level-relativelevel to toggle whether the window is always on top or not, and when they close and then open the Fether window again it should save their previous setting.

By default we want it to be Always On Top to be disabled, such that if the user clicks elsewhere on the screen it blurs the Fether window (moves it behind the other window that the user clicked) rather than actually closing it), as mentioned in https://github.com/paritytech/fether/issues/411

**Comment by Tbaut** [comment]
Closing this for now.
