### ISSUE TITLE
Window height bounces and loads at incorrect height

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#418]
The animation that was introduced in this PR https://github.com/paritytech/fether/pull/409 sometime causes the Window height to load to the incorrect height causing much of the contents to be cropped. Proposed solution is to remove the animation.

**Comment by Tbaut** [comment]
I think we should simply have a constant size https://github.com/paritytech/fether/issues/275
Also this is helpful to make the UI consistent when Fether will be a mobile app. Also when Fether is positioned at the bottom (some linux and windows) right now the window jumps as in, it's not touching the task bar) and it doesn't look good.
