### ISSUE TITLE
Blank screen shown when changing from Account (token list) page to the Send Ether/THIBCoin page

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#420]
On the Account List page, if I click an account it takes me to its Account page (which shows the token list associated with the account). If I then click on the Ether or THIBCoin card, it always shows a blank screen before it has loaded the Send Ether or Send THIBCoin page.

The blank screen doesn't usually last very long, but still the user may be left wondering why there isn't a loading screen (i.e. "Loading transaction page..." or similar) so they're confident nothing has gone wrong.

Since it's changing the route, we can't use the same approach as was done in this commit https://github.com/paritytech/fether/commit/854f1b4512823259832d5e9a237f3a6b27a8ae21

**Comment by amaurymartiny** [comment]
@ltfschoen Can you try if #414 solves your problem? It still has some corner-case bugs, but should mostly work as you'd expect (no loading screen at all).
