### ISSUE TITLE
Fether menu constantly visible on windows and does not appear when pressing ALT on Linux

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#429]
As reported here https://github.com/paritytech/fether/pull/415#issuecomment-464634062 on Linux Mint (cinnamon window manager) it does not have the Menu that appears when pressing `alt`.

**Comment by axelchalon** [comment]
On current master, whether using `yarn start` or the packaged binary, Fether launches without menu bar / frame and pressing alt doesn't do anything. (wm: bspwm) testing on KDE now..

**Comment by Tbaut** [comment]
Tested master on windows and the menu appears although I havn't pressed `alt`. Pressing it does nothing. The footer is therefore hidden.

**Comment by ltfschoen** [comment]
> Tested master on windows 10 and the menu appears although I havn't pressed `alt`. Pressing it does nothing. The footer is therefore constantly hidden.

* @Tbaut yes, the causes are because it's configured to show it with a "frame" instead of "frameless" on Windows OS.

**fether-electron/src/main/app/options/config/index.js**
```
const shouldUseFrame = process.platform === 'win32';
```

It's also caused because I settled for the following configuration, which shows the menu bar all the time on Windows OS. But when it's configured to be shown all the time it prevents the user from toggling it with the ALT key, so at the moment it is incorrectly showing the tray balloon (only supported on Windows OS) that indicates that the user can "Press ALT in the Fether window to toggle the menu". 

**fether-electron/src/main/app/methods/setupMenu.js** 
```
fetherApp.win.setAutoHideMenuBar(false); // Pressing ALT shows menu bar
fetherApp.win.setMenuBarVisibility(true);
```

I initially chose to show the menu bar all the time on Windows OS because if I allowed the user to toggle it with the ALT key, the bottom of the window would be cropped so the "Feedback" button would only be partially visible. However I thought I'd corrected that with the following code:

**fether-electron/src/main/app/messages/index.js**

```
const height =
  process.platform === 'win32' && fetherAppWindow.isMenuBarVisible()
    ? resizeHeight + feedbackButtonHeight
    : resizeHeight;
```

Perhaps it's just a matter of changing it to `fetherApp.win.setAutoHideMenuBar(true);` in **fether-electron/src/main/app/methods/setupMenu.js**

**Comment by ltfschoen** [comment]
@axelchalon On Ubuntu Gnome, I have to "hold down" the "Left ALT" key and then the menu appears at the top of the screen. However, as you've pointed out it doesn't appear to work consistently on a different Linux OS.

Could you try changing `const shouldUseFrame = process.platform === 'win32';` to `const shouldUseFrame = true;` in fether-electron/src/main/app/options/config/index.js, and then see if you can get the menu to appear on bspwm and KDE?

If that works I think on all Linux OS (i.e. `process.platform === 'linux'`) we should make the Fether window have a "frame" by default.

And we might have to use methods of the `os` library to be more granularly configure it to work on different versions of Linux. What does the following return when you run `node` in the terminal and then copy/paste the following? Could you try on both bspwm and KDE please?

```
import os from 'os';
console.log(os.type());
console.log(os.release());
console.log(os.platform());
```

**Comment by ltfschoen** [comment]
I think we should cater for different OS types as we've done here https://github.com/paritytech/scripts/pull/56/files

**Comment by axelchalon** [comment]
Holding down alt has no effect either on my side.

Using `const shouldUseFrame = true;` Fether still launches with a frameless window but the menu bar is visible, so it's now possible to quit.

**Comment by Tbaut** [comment]
Closing since we show not to need this "alt" behavior
