### ISSUE TITLE
Can't Add Tokens

### ISSUE THREAD

**Issue by housemobile** [paritytech/fether#441]
Add Tokens --> Find token by name or symbol

I've tried many ERC20 tokens, both by name, symbol or contract address. Nothing happens after I enter it in the field.

**Comment by Tbaut** [comment]
Thanks for your question. Right now we use the legacy "Parity Token registry". It lacks many tokens and you can't easily add any token to it. This will be solved very soon in https://github.com/paritytech/fether/issues/267 where we will switch to using https://github.com/ethereum-lists/tokens/
