### ISSUE TITLE
[Windows] Fether window height decreases each time it's shown/hidden

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#442]
As discovered by @Tbaut, on Windows OS, when you drag the Fether window below the bottom of the screen, each time you do it the Fether window height decreases!

We found that the cause was because the the 'resize' event listener in setupWinListeners does run on Windows 10 (incorrectly thought it didn't) in addition to the hook in setupWin32Listeners that runs also on Windows 10 (but it runs on both moved and resize events instead of just resize).

added by Thibaut: 
Another way to reproduce:
    * click several times on the taskbar icon, so that is shows and hide Fether. Notice how the windows shrinks.

**Comment by ltfschoen** [comment]
Noted by @Tbaut that this only happens when the Fether window isn't "frameless"

**Comment by Tbaut** [comment]
> Noted by @Tbaut that this only happens when the Fether window isn't "frameless"

That's a misunderstanding, I was talking about the window on Windows that is 446px instead of 515px as asked.
