### ISSUE TITLE
Blank screen only on Windows 10 Virtual Machine

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#446]
When I run the latest "master" branch on a Windows 10 Virtual Machine. The UI just shows the frame and the menu, but the account list page is a blank screen. I don't have this issue on a Linux Mint Virtual Machine or macOS (without VM) where it shows the health status in the footer.

In the terminal it displays `Blocked connection from parity://1.ui.parity using invalid token.`, and in the browser dev tools console it displays `WebSocket connection to 'ws://127.0.0.1:8546/' failed: Error during WebSocket handshake: Unexpected response code: 403.`

<img width="767" alt="screen shot 2019-02-24 at 3 05 53 pm" src="https://user-images.githubusercontent.com/6226175/53300949-849c8c00-384d-11e9-8d2b-72fa735dfe61.png">

<img width="404" alt="screen shot 2019-02-24 at 4 02 42 pm" src="https://user-images.githubusercontent.com/6226175/53300977-a7c73b80-384d-11e9-830e-1c8a9a0693ff.png">

If I switch to an older commit in the "master" branch when we first introduced the taskbar app, and before we removed the overlay on the account list screen, it at least shows an overlay message in the UI "Connecting to the node...", or the not connected to the internet message if you disconnect the internet, rather than nothing at all

<img width="662" alt="screen shot 2019-02-24 at 3 20 38 pm" src="https://user-images.githubusercontent.com/6226175/53300992-d9400700-384d-11e9-88dd-1424502c53c5.png">

**Comment by Tbaut** [comment]
If this only happens on virtual machine, then I would not consider this as very

**Comment by ltfschoen** [comment]
Update: I've tried the following **without** success

I've tried updating packages/fether-electron/src/main/app/parityEthereum/index.js, so Parity Ethereum is run with additional flags `--ws-interface all --ws-apis all --ws-origins all --ws-hosts all --jsonrpc-apis all --jsonrpc-hosts all --jsonrpc-cors all --ipc-apis all` by I still get the same error.

I've turned off Windows Defender Firewall

Note that the Browser Dev tools displays the following error (403 Forbidden)

<img width="574" alt="Screen Shot 2019-03-19 at 11 28 52 am" src="https://user-images.githubusercontent.com/6226175/54599131-4b190400-4a3a-11e9-96dd-d0536f7ad0c1.png">
