### ISSUE TITLE
Be able to remove accounts from wallet

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/fether#448]
self-explanatory. Though I couldn't find this issue having been raised before, I imagine this has already been discussed offline and there's a reason it doesn't yet exist? If not, I think this is a pretty useful feature to have.

**Comment by Tbaut** [comment]
I don't think we've spoke about it too much. I see it as a menu entry in the dropdown menu from an account.
Deletion should only happen after:
- account unlock (password)

In case of a signer account
- Telling that the account won't be visible on Fether but can be added back any time from Signer.

In case it's a "normal" account
- Warning telling that the account will be definitely lost if no backup was made (JSON or recovery phrase)
