### ISSUE TITLE
Show when loading more tokens

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#449]
Loading tokens (actually token balance) can take some time and the tokens cards only appear when the RPC got answered. I'd like to know as a user that the tokens are loading.

Either by showing a loader under the cards that are displayed already or by showing the tokens, but hiding temporarily the balance (and prevent the card from being clickable) while the balance gets retrieved.

2 alternatives that I like equally. Pick the one you prefer or the easiest to be implemented.
![image](https://i.imgur.com/C8yygAM.gif)

**Comment by ltfschoen** [comment]
I think this PR https://github.com/paritytech/fether/pull/414 will resolve this issue using the 2nd alternative

**Comment by Tbaut** [comment]
closing as addressed
