### ISSUE TITLE
Clicking "Show/Hide Window" when Fether window is blurred currently hides the window instead of showing it

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#453]
When the Fether window is blurred (behind other windows), then if I want to bring it to the front I would have expected the "Show/Hide Window" item when right clicking the tray icon to bring it to the front, but instead it just completely hides the window that is already blurred.

**Comment by Tbaut** [comment]
Yes, I agree that's annoying. FWIW Riot app does the same. It'd be great to have it work.
