### ISSUE TITLE
Can't send transaction with a Signer account

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#456]
For the record as it seems related to the light client.

Tested with `master` on Kovan

How to reproduce:
- Bind a Parity Signer account with Fether
- Send some funds from it
- get stuck on the `Sending you transaction` screen with the folowing console error
```
ws.js:330 eth_getTransactionReceipt(["0x400ddca29de5256e53f59cebc62d3823e65a8d71499f67135ec38552e1ed5c13"]): -32042: Bad response on request: [ TransactionIndex ]. Error cause was EmptyResponse, (majority count: 54 / total: 54)
ws.js:330 eth_getTransactionReceipt(["0x400ddca29de5256e53f59cebc62d3823e65a8d71499f67135ec38552e1ed5c13"]): -32042: Bad response on request: [ TransactionIndex ]. Error cause was EmptyResponse, (majority count: 28 / total: 28)
ws.js:330 eth_getTransactionReceipt(["0x400ddca29de5256e53f59cebc62d3823e65a8d71499f67135ec38552e1ed5c13"]): -32042: Bad response on request: [ TransactionIndex ]. Error cause was EmptyResponse, (majority count: 51 / total: 51)
```

**Comment by ltfschoen** [comment]
I get the same console error also when trying to send between two non-Parity Signer accounts.
First it shows error `eth_getTransactionReceipt` when theUI displays 'Sending you transaction', then it eventually shows confirmed, and eventually displays 'Transaction Confirmed'.

But if I try and send Ether from a Parity Signer account, on the Send Ether page after entering values for the fields it displays the 'Estimating Gas...' popup, which doesn't go away.
