### ISSUE TITLE
Unable to load webcam to scan QR code in Fether even though webcam is working

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#466]
I'm using macOS 10.14 Mojave. If I try and send a transaction from a Parity Signer account, after I enter a recipient address, an amount, and click "Scan", and then scan the QR code using Parity Signer and click "Sign Transaction" on my mobile device, then when I click "Next Step" in Fether it displays "Webcam hardware error. Try restarting your computer", which corresponds to a `NotReadableError` occuring in fether-react/src/Scanner/Scanner.js. Restarting the computer does not resolve the issue. I've debugged the error in the catch block to be `DOMException: Could not start video source`.

Note that running `sudo killall VDCAssistant; sudo killall AppleCameraAssistant` does not resolve the issue.

Note that I have all the latest Software Updates installed.

However, if I go to "Finder > Applications >  PhotoBooth", it opens and the FaceTime HD Camera (built-in) webcam starts working immediately with the green light illuminated on the screen.

The solution will need to update the error message that corresponds to `NotReadableError`, since restarting the computer may not be enough.

**Comment by Tbaut** [comment]
Thanks for figuring that out. I think we have tons of info in the Readme right now that would probably fit better in a wiki. I'll figure out if we should use wiki.parity.io (there's a [FAQ for Fether](https://wiki.parity.io/Fether-FAQ#how-to-delete-an-account)) or if we should use github's wiki

**Comment by ltfschoen** [comment]
This is a known macOS issue on Mojave 10.14 and only happens in development environment when running an Electron app. It was necessary to go to System Preferences > Security & Privacy > Privacy > Camera, and ensure that the checkbox for the "Terminal" app is checked. See https://github.com/electron/electron/issues/14801#issuecomment-478343983

**Comment by ltfschoen** [comment]
I've created these two PRs to address this issue:
* Fether PR https://github.com/paritytech/fether/pull/482
* Parity Wiki PR https://github.com/paritytech/wiki/pull/320

**Comment by ltfschoen** [comment]
Closing as the PRs mentioned address the issue
