### ISSUE TITLE
EDIT: Fether UI does use ssh-connected node first

### ISSUE THREAD

**Issue by stone212** [paritytech/fether#490]
Parity 2.3.8 on remote server

1. Connecting by ssh tunnel:

`ssh -N -L 8545:localhost:8545 -L 8546:localhost:8546 user@parityserver`

2. Start fether:

`$ ./fether-0.2.0-x86_64.AppImage`

3. Choose not to integrate with your system

4. See display:

`Connecting to Node`

5. See failure:

`Downloading Parity`

Expect it would not try "Downloading Parity" because there is already a local node.

EDIT: If you wait for the "Download" to complete you see the accounts on the remote server.  So it must be using the tunnel.  But it does not indicate so.

And why does it take time for "Downloading"?  Console says:

```
[2019-04-03T09:26:56.972Z] INFO (@parity/electron:main/1327 on StillRollin-MISC): Another instance of parity is running, closing local instance.
```

So maybe it does not check for tunnel until after it downloads.  This is a bandwidth waste and also a security problem for people who may have issues disclosing use of crypto nodes to ISP etc.

**Comment by Tbaut** [comment]
Thanks for the issue. The downloading part is tricked in this case it seems. We've removed the download part as Fether will come with an embedded parity node from the next release on. Note that in your case, you will need to run a certain version of Parity to ensure Fether compatibility. (e.g, the next release will expect parity ~2.4).

Any way you can try it from the source to confirm it's fixed?

**Comment by stone212** [comment]
Well when I compile Parity is downloaded during yarn install.  So already I have Parity on my system and I do not need it because I will use a tunnel.

```
fresh packages...
$ cd scripts && node ./fetch-latest-parity.js
Downloading Parity Ethereum v2.4.4... (https://releases.parity.io/ethereum/v2.4.4/x86_64-unknown-linux-gnu/parity)
Success: bundled Parity Ethereum v2.4.4
Done in 512.42s.
```

So really there is nothing better with this version.  I confirm when I start the tunnel and start electron app (`yarn electron`) it connects to the tunnel node.  It gives me an error that it requires 2.4 like you said.  I only use stable versions of course because this is not a testing project but soon I am sure 2.4 will be stable and the error tells me it connects to the tunnel.  But it still downloads Parity.

**Comment by Tbaut** [comment]
right, after our discussion on Gitter it turns out that Fether is not appropriate for what you are looking for as it is meant to be an interface for a light client. running it on top of a full node makes it lose all its interest.

**Comment by stone212** [comment]
@Tbaut Yes but it's the best available at the moment and it will be a nice light client when it's done.  But I don't like the term "light client" if you are downloading a node locally.  That is the opposite of light client would you agree?  A full client requires a local node, like `bitcoind`.  A light client has the node remotely hosted like electrum.  Anyway fether is good and I will use it for some things.  I am trying to find a solution so that the full functionality of a Parity node can be used without me doing all the work for the most lazy people in the world: progammers.  :)

**Comment by stone212** [comment]
@Tbaut Is it really so difficult to disable downloading the node until after it checks if there is already something responding on port 8545?  Obviously I don't know so mabe the answer is "yes it is difficult".

**Comment by Tbaut** [comment]
>But I don't like the term "light client" if you are downloading a node locally. That is the opposite of light client would you agree? 

No, the main distinction between a `light` and a `full` node is how the node verifies the blockchain, and whether this requires to download the blocks' body or not. The footprint of a light node is much smaller than a full node.

>A light client has the node remotely hosted like electrum.

What you describe is a thin client. For more info, I've written about light clients here: https://www.parity.io/what-is-a-light-client/

>@Tbaut Is it really so difficult to disable downloading the node

It's not about difficulty, it's about what is the use case the software was built for. If you don't want a node, then you don't want to use Fether for what it's been made for. Now because it's open source, you can still take it and modify it for your specific use case.

**Comment by stone212** [comment]
@Tbaut Thank you for correcting me.  I see the distinction and I prefer your terminology.  Thin client is like an old terminal client on a VAX then.  As it should be.  

> It's not about difficulty,... Now because it's open source, you can still take it and modify it for your specific use case.

That's why I am asking about the difficulty. :)

**Comment by axelchalon** [comment]
If you don't want Parity Ethereum to be downloaded I think you can just remove this line https://github.com/paritytech/fether/blob/d0ae207176fd28b8e986e01499f749c4e676c40a/package.json#L43

**Comment by stone212** [comment]
@axelchalon Yes I saw that.  But then I'd be re-building it and distributing it to my users with every release.  Maybe I'll make a PR.  Do you think the right code would be: run a curl test first to see if there is a node and only if not do the fetch-latest-parity?  That is how I would do it in BASH.

**Comment by stone212** [comment]
@axelchalon So you're saying I should not make the change and pull request.  Okay.  I am not sure why you suggested the change above if you would reject it?

**Comment by axelchalon** [comment]
I thought this might be useful for you if you wanted to fork Fether to taylor it to your own needs

**Comment by stone212** [comment]
@axelchalon I see.  We would have to re-fork with every release based on what the team decided but thank you.
