### ISSUE TITLE
Linux: close button

### ISSUE THREAD

**Issue by ianaz** [paritytech/fether#502]
Hi guys, nice job! 
I can't find how to close the application on **Ubuntu 18.04.1 LTS** tho (except obviously terminal)..?

![image](https://user-images.githubusercontent.com/1556466/55874510-da758b00-5b92-11e9-9dde-da65d2f658b0.png)

**Comment by Tbaut** [comment]
Hey, thanks for trying it out. you should see a tray icon for Fether like here at the bottom right (if you are on gnome, it's probably at the top right). Left-click> Quit should allow you to close Fether.
![image](https://user-images.githubusercontent.com/33178835/55875070-650aba00-5b94-11e9-90fd-84e7bb4fe5b6.png)

**Comment by ianaz** [comment]
Thanks for the quick answer @Tbaut ! So not having a close button directly on the UI has been done on purpose, right?

**Comment by Tbaut** [comment]
Right, it's "on purpose" not in the sens we want to annoy anyone or prevent you from closing it. Just that having the window decoration (frame + minmize/max/close) wasn't as nice as a frameless window.

It's a very valuable feedback, and if we realize that many user report this "annoyance" we can go back to a framed app.
