### ISSUE TITLE
Can't import Signer account/address

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/fether#508]
I'm trying to import/recover a Signer account that is not in my account list in Fether. When scanning the account QR code, Fether prints: "Account [...] already listed" 

Also, shouldn't it say `Import from Parity Signer` rather than `Recover from Parity Signer`?

**Comment by Tbaut** [comment]
Can you confirm that the account you want to import is for the chain (mainnet or kovan)?
Fether only list the accounts that match the current chain.

This should be addressed by https://github.com/paritytech/fether/pull/483

**Comment by bjornwgnr** [comment]
> Can you confirm that the account you want to import is for the chain Fether currently synced (e.g mainnet or kovan)?

Right, the account was indeed for a different chain.

**Comment by bjornwgnr** [comment]
@Tbaut What do you think about `Import from Parity Signer` rather than `Recover from Parity Signer`?
