### ISSUE TITLE
Syncing screen preventing to do anything else

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#51]
When the node goes out of sync, we are showing a big screen that breaks the user flow (and removes the focus on some field if it happens when typing the password for instance).

As suggested by Amaury we should:
- make this "sync" much less intrusive: what about making the little icon at the bottom left orange and show "Syncing" instead of the green "Sync".
- Only show the "Syncing" state when out of sync for more than 10sec?
 
![image](https://user-images.githubusercontent.com/33178835/41459165-03b78a22-7089-11e8-8c3d-78134cdb0e81.png)

**Comment by TriplEight** [comment]
Sometimes `syncing 100%` screen appears above any screen and shows, removing the focus from the field.

**Comment by axelchalon** [comment]
should be fixed with https://github.com/paritytech/fether/pull/216 (overlay will only appear in the transaction form/signer and only if the "syncing" takes more than 2 seconds; the focus will still be removed though (and any other info we input, hmm))

**Comment by Tbaut** [comment]
This is solved now.
