### ISSUE TITLE
Flight Mode in Android

### ISSUE THREAD

**Issue by TomaszWaszczyk** [paritytech/fether#527]
I think would be cool to enable flight mode on device where the Fether is installed to save energy and boost security.

Write it in the docs.

**Comment by Tbaut** [comment]
Hey Tomasz,
Not sure I can follow you. Fether isn't meant for Android, and even in this case, the underlying light node needs some kind of connectivity to sync with the chain.

**Comment by TomaszWaszczyk** [comment]
Mea culpa. Bad place. Will post in the right place.
