### ISSUE TITLE
Testing Fether - Ability to copy address

### ISSUE THREAD

**Issue by btcmacroecon** [paritytech/fether#530]
It would be nice to be able to "open" up Fether so one can copy the entire address with "copy" as when it is syncing, or when looking at several accounts, there is not the ability to "copy". Therefore it would be nice to be able to open up the UI or have the ability to copy addresses when looking at several, given that Parity UI is defunct and users need to input the tokens they have. It would speed up the process for ease of use. Perhaps there is a way but I cannot tell there is.

**Comment by Tbaut** [comment]
To copy one address you can click on it on the address view. You can't copy it from the general overview indeed if this is what you meant.

**Comment by btcmacroecon** [comment]
No there are a couple of addresses that never allows me to copy it, or just
syncing or something.  Just playing around with fether! Just trying to add
a couple of tokens but can't figure out which ones. Nothing critical going
on, but testing fether post parity

**Comment by Tbaut** [comment]
I'm sorry but it isn't entirely clear to me what doesn't work as expected. You should be able to copy addresses any time, whether you are synced or not. Could you provide a screenshot?

**Comment by btcmacroecon** [comment]
As you can see from screenshot there is no address to copy. I don't have
ability to copy when it does this. thx for follow up

**Comment by Tbaut** [comment]
It looks like the "answer by email" from Github doesn't handle screenshots. Can you please paste the image in Github or give a link to it?

**Comment by btcmacroecon** [comment]
![fetherscreenshotA](https://user-images.githubusercontent.com/7543793/59657111-8ff52980-9154-11e9-8079-61787326e393.png)

**Comment by Tbaut** [comment]
Understood, this looks like a bug.
Can you open the console using ctrl-shift-j and post a screenshot of any error that appears here?

Was this account imported or created with Fether?

**Comment by btcmacroecon** [comment]
![fetherbug18th](https://user-images.githubusercontent.com/7543793/59736797-ea06f500-920f-11e9-9ab3-9ed7e549ff3d.png) OK I closed tabs, and hit control, shift, j and this is image I took. 
The account was imported, as I am attempting getting all my Parity accounts moved over to Fether because UI at Parity didn't display my accounts, so I need greater accountability. Thanks

**Comment by Tbaut** [comment]
This appears to be the console of your navigator and not from the Fether application.

Note that Fether is in beta and should not be used for your usual accounts.

**Comment by btcmacroecon** [comment]
But Parity went blank and I had my account information there. I was merely trying to get my accounts back, as I could no longer see it and it was no longer supported. I set up all my accounts based on import, had to do something. Had Parity left it so I could have access to my accounts or at least see them, I could have done something but when it went blank, I had to like go into salvage mode.
