### ISSUE TITLE
Deprecation warning: "UTC parity_accountsInfo is deprecated and will be removed in future versions"

### ISSUE THREAD

**Issue by adamryczkowski** [paritytech/fether#533]
During the initial synchronization I've come accross the following message in the standard output: 

```
UTC parity_accountsInfo is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives
```

I do not know the inner working of the Fether, but the warning itself sounds alarming. Does it mean that the fether will soon stop working? Will you provide a patch? (Is the fether still maintained anyway?)

**Comment by Tbaut** [comment]
The number mentioned is an issue number for Parity Ethereum: https://github.com/paritytech/parity-ethereum/issues/9997 We have an issue open for this already on Fether repo_ https://github.com/paritytech/fether/issues/148
The split for account management in Parity Ethereum is not something that will be done overnight, I invite you to read this issue carefully, you will see [here for instance](https://github.com/paritytech/parity-ethereum/issues/9997#issuecomment-481994697) that when it happens, there will be alternatives.
