### ISSUE TITLE
Place error labels on top of the problematic field

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#80]
When mistyping a too big amount compared to the balance or a wrong address, the error only shows on mouse hover the grayed "send" button.
It should appear automatically either on defocus of the field or when clicking on send.

Additionally, when no password is entered and "send tx" is clicked there is no feedback

![image](https://user-images.githubusercontent.com/33178835/41775104-d0b21210-7622-11e8-9f87-42b943c8e36b.png)

**Comment by amaurymartiny** [comment]
[Note to self] Code-wise: Use a React form validation library for that, I'm writing too much boilerplate already.

**Comment by amaurymartiny** [comment]
I'll use a react library for form validation (instead of writing all boilerplate code myself) so it might take time to reorganize some code.

I'll do this as lowest priority of 1.0.
