### ISSUE TITLE
UX First start opens first account

### ISSUE THREAD

**Issue by 5chdn** [paritytech/fether#88]
I would prefer to see all my accounts first.

**Comment by amaurymartiny** [comment]
Do you mean every time you start Fether?

It's debatable, I would prefer to see my last opened account, I think that's what we agreed with @brianflanagan. I suppose the average user won't switch accounts that much?

**Comment by 5chdn** [comment]
It just makes no sense to start not on top level, that's a major usability confusion. Was surprised that I was able to "go back" to the dashboard without ever "going in" to a specific account.

**Comment by axelchalon** [comment]
This is the default behaviour since https://github.com/paritytech/fether/pull/184 afaik
